%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'Search_irf';
M_.dynare_version = '4.5.6';
oo_.dynare_version = '4.5.6';
options_.dynare_version = '4.5.6';
%
% Some global variables initialization
%
global_initialization;
diary off;
options_.console_mode = 1;
options_.nodisplay = 1;
M_.exo_names = 'eps_kappa';
M_.exo_names_tex = 'eps\_kappa';
M_.exo_names_long = 'eps_kappa';
M_.exo_names = char(M_.exo_names, 'eps_varrho');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_varrho');
M_.exo_names_long = char(M_.exo_names_long, 'eps_varrho');
M_.exo_names = char(M_.exo_names, 'eps_varomega');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_varomega');
M_.exo_names_long = char(M_.exo_names_long, 'eps_varomega');
M_.exo_names = char(M_.exo_names, 'eps_rhox');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_rhox');
M_.exo_names_long = char(M_.exo_names_long, 'eps_rhox');
M_.exo_names = char(M_.exo_names, 'eps_z');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_z');
M_.exo_names_long = char(M_.exo_names_long, 'eps_z');
M_.exo_names = char(M_.exo_names, 'eps_a');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_a');
M_.exo_names_long = char(M_.exo_names_long, 'eps_a');
M_.exo_names = char(M_.exo_names, 'eps_yCo');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_yCo');
M_.exo_names_long = char(M_.exo_names_long, 'eps_yCo');
M_.exo_names = char(M_.exo_names, 'eps_g');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_g');
M_.exo_names_long = char(M_.exo_names_long, 'eps_g');
M_.exo_names = char(M_.exo_names, 'eps_Rstar');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_Rstar');
M_.exo_names_long = char(M_.exo_names_long, 'eps_Rstar');
M_.exo_names = char(M_.exo_names, 'eps_pistar');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_pistar');
M_.exo_names_long = char(M_.exo_names_long, 'eps_pistar');
M_.exo_names = char(M_.exo_names, 'eps_zetao');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_zetao');
M_.exo_names_long = char(M_.exo_names_long, 'eps_zetao');
M_.exo_names = char(M_.exo_names, 'eps_zetau');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_zetau');
M_.exo_names_long = char(M_.exo_names_long, 'eps_zetau');
M_.exo_names = char(M_.exo_names, 'eps_ystar');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_ystar');
M_.exo_names_long = char(M_.exo_names_long, 'eps_ystar');
M_.exo_names = char(M_.exo_names, 'eps_pCostar');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_pCostar');
M_.exo_names_long = char(M_.exo_names_long, 'eps_pCostar');
M_.exo_names = char(M_.exo_names, 'eps_eR');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_eR');
M_.exo_names_long = char(M_.exo_names_long, 'eps_eR');
M_.exo_names = char(M_.exo_names, 'eps_aux');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_aux');
M_.exo_names_long = char(M_.exo_names_long, 'eps_aux');
M_.endo_names = 'lam';
M_.endo_names_tex = 'lam';
M_.endo_names_long = 'lam';
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'theta');
M_.endo_names_tex = char(M_.endo_names_tex, 'theta');
M_.endo_names_long = char(M_.endo_names_long, 'theta');
M_.endo_names = char(M_.endo_names, 'chitil');
M_.endo_names_tex = char(M_.endo_names_tex, 'chitil');
M_.endo_names_long = char(M_.endo_names_long, 'chitil');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'm');
M_.endo_names_tex = char(M_.endo_names_tex, 'm');
M_.endo_names_long = char(M_.endo_names_long, 'm');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'rho');
M_.endo_names_tex = char(M_.endo_names_tex, 'rho');
M_.endo_names_long = char(M_.endo_names_long, 'rho');
M_.endo_names = char(M_.endo_names, 's');
M_.endo_names_tex = char(M_.endo_names_tex, 's');
M_.endo_names_long = char(M_.endo_names_long, 's');
M_.endo_names = char(M_.endo_names, 'e');
M_.endo_names_tex = char(M_.endo_names_tex, 'e');
M_.endo_names_long = char(M_.endo_names_long, 'e');
M_.endo_names = char(M_.endo_names, 'thetaL');
M_.endo_names_tex = char(M_.endo_names_tex, 'thetaL');
M_.endo_names_long = char(M_.endo_names_long, 'thetaL');
M_.endo_names = char(M_.endo_names, 'Ebar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ebar');
M_.endo_names_long = char(M_.endo_names_long, 'Ebar');
M_.endo_names = char(M_.endo_names, 'Estar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Estar');
M_.endo_names_long = char(M_.endo_names_long, 'Estar');
M_.endo_names = char(M_.endo_names, 'U');
M_.endo_names_tex = char(M_.endo_names_tex, 'U');
M_.endo_names_long = char(M_.endo_names_long, 'U');
M_.endo_names = char(M_.endo_names, 'Delbar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Delbar');
M_.endo_names_long = char(M_.endo_names_long, 'Delbar');
M_.endo_names = char(M_.endo_names, 'Delstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Delstar');
M_.endo_names_long = char(M_.endo_names_long, 'Delstar');
M_.endo_names = char(M_.endo_names, 'wstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'wstar');
M_.endo_names_long = char(M_.endo_names_long, 'wstar');
M_.endo_names = char(M_.endo_names, 'epsi');
M_.endo_names_tex = char(M_.endo_names_tex, 'epsi');
M_.endo_names_long = char(M_.endo_names_long, 'epsi');
M_.endo_names = char(M_.endo_names, 'mu');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu');
M_.endo_names_long = char(M_.endo_names_long, 'mu');
M_.endo_names = char(M_.endo_names, 'Fstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Fstar');
M_.endo_names_long = char(M_.endo_names_long, 'Fstar');
M_.endo_names = char(M_.endo_names, 'Wstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Wstar');
M_.endo_names_long = char(M_.endo_names_long, 'Wstar');
M_.endo_names = char(M_.endo_names, 'Wbar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Wbar');
M_.endo_names_long = char(M_.endo_names_long, 'Wbar');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'wbar');
M_.endo_names_tex = char(M_.endo_names_tex, 'wbar');
M_.endo_names_long = char(M_.endo_names_long, 'wbar');
M_.endo_names = char(M_.endo_names, 'wtil');
M_.endo_names_tex = char(M_.endo_names_tex, 'wtil');
M_.endo_names_long = char(M_.endo_names_long, 'wtil');
M_.endo_names = char(M_.endo_names, 'h');
M_.endo_names_tex = char(M_.endo_names_tex, 'h');
M_.endo_names_long = char(M_.endo_names_long, 'h');
M_.endo_names = char(M_.endo_names, 'yC');
M_.endo_names_tex = char(M_.endo_names_tex, 'yC');
M_.endo_names_long = char(M_.endo_names_long, 'yC');
M_.endo_names = char(M_.endo_names, 'xH');
M_.endo_names_tex = char(M_.endo_names_tex, 'xH');
M_.endo_names_long = char(M_.endo_names_long, 'xH');
M_.endo_names = char(M_.endo_names, 'xF');
M_.endo_names_tex = char(M_.endo_names_tex, 'xF');
M_.endo_names_long = char(M_.endo_names_long, 'xF');
M_.endo_names = char(M_.endo_names, 'yH');
M_.endo_names_tex = char(M_.endo_names_tex, 'yH');
M_.endo_names_long = char(M_.endo_names_long, 'yH');
M_.endo_names = char(M_.endo_names, 'yF');
M_.endo_names_tex = char(M_.endo_names_tex, 'yF');
M_.endo_names_long = char(M_.endo_names_long, 'yF');
M_.endo_names = char(M_.endo_names, 'pm');
M_.endo_names_tex = char(M_.endo_names_tex, 'pm');
M_.endo_names_long = char(M_.endo_names_long, 'pm');
M_.endo_names = char(M_.endo_names, 'ptilH');
M_.endo_names_tex = char(M_.endo_names_tex, 'ptilH');
M_.endo_names_long = char(M_.endo_names_long, 'ptilH');
M_.endo_names = char(M_.endo_names, 'ptilF');
M_.endo_names_tex = char(M_.endo_names_tex, 'ptilF');
M_.endo_names_long = char(M_.endo_names_long, 'ptilF');
M_.endo_names = char(M_.endo_names, 'fH');
M_.endo_names_tex = char(M_.endo_names_tex, 'fH');
M_.endo_names_long = char(M_.endo_names_long, 'fH');
M_.endo_names = char(M_.endo_names, 'fF');
M_.endo_names_tex = char(M_.endo_names_tex, 'fF');
M_.endo_names_long = char(M_.endo_names_long, 'fF');
M_.endo_names = char(M_.endo_names, 'mcH');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcH');
M_.endo_names_long = char(M_.endo_names_long, 'mcH');
M_.endo_names = char(M_.endo_names, 'mcF');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcF');
M_.endo_names_long = char(M_.endo_names_long, 'mcF');
M_.endo_names = char(M_.endo_names, 'rK');
M_.endo_names_tex = char(M_.endo_names_tex, 'rK');
M_.endo_names_long = char(M_.endo_names_long, 'rK');
M_.endo_names = char(M_.endo_names, 'v');
M_.endo_names_tex = char(M_.endo_names_tex, 'v');
M_.endo_names_long = char(M_.endo_names_long, 'v');
M_.endo_names = char(M_.endo_names, 'rhon');
M_.endo_names_tex = char(M_.endo_names_tex, 'rhon');
M_.endo_names_long = char(M_.endo_names_long, 'rhon');
M_.endo_names = char(M_.endo_names, 'ctil');
M_.endo_names_tex = char(M_.endo_names_tex, 'ctil');
M_.endo_names_long = char(M_.endo_names_long, 'ctil');
M_.endo_names = char(M_.endo_names, 'hC');
M_.endo_names_tex = char(M_.endo_names_tex, 'hC');
M_.endo_names_long = char(M_.endo_names_long, 'hC');
M_.endo_names = char(M_.endo_names, 'imp');
M_.endo_names_tex = char(M_.endo_names_tex, 'imp');
M_.endo_names_long = char(M_.endo_names_long, 'imp');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'xi');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi');
M_.endo_names_long = char(M_.endo_names_long, 'xi');
M_.endo_names = char(M_.endo_names, 'rer');
M_.endo_names_tex = char(M_.endo_names_tex, 'rer');
M_.endo_names_long = char(M_.endo_names_long, 'rer');
M_.endo_names = char(M_.endo_names, 'piS');
M_.endo_names_tex = char(M_.endo_names_tex, 'piS');
M_.endo_names_long = char(M_.endo_names_long, 'piS');
M_.endo_names = char(M_.endo_names, 'xHstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'xHstar');
M_.endo_names_long = char(M_.endo_names_long, 'xHstar');
M_.endo_names = char(M_.endo_names, 'pH');
M_.endo_names_tex = char(M_.endo_names_tex, 'pH');
M_.endo_names_long = char(M_.endo_names_long, 'pH');
M_.endo_names = char(M_.endo_names, 'pF');
M_.endo_names_tex = char(M_.endo_names_tex, 'pF');
M_.endo_names_long = char(M_.endo_names_long, 'pF');
M_.endo_names = char(M_.endo_names, 'DelH');
M_.endo_names_tex = char(M_.endo_names_tex, 'DelH');
M_.endo_names_long = char(M_.endo_names_long, 'DelH');
M_.endo_names = char(M_.endo_names, 'DelF');
M_.endo_names_tex = char(M_.endo_names_tex, 'DelF');
M_.endo_names_long = char(M_.endo_names_long, 'DelF');
M_.endo_names = char(M_.endo_names, 'dstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'dstar');
M_.endo_names_long = char(M_.endo_names_long, 'dstar');
M_.endo_names = char(M_.endo_names, 'tb');
M_.endo_names_tex = char(M_.endo_names_tex, 'tb');
M_.endo_names_long = char(M_.endo_names_long, 'tb');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'yNM');
M_.endo_names_tex = char(M_.endo_names_tex, 'yNM');
M_.endo_names_long = char(M_.endo_names_long, 'yNM');
M_.endo_names = char(M_.endo_names, 'pY');
M_.endo_names_tex = char(M_.endo_names_tex, 'pY');
M_.endo_names_long = char(M_.endo_names_long, 'pY');
M_.endo_names = char(M_.endo_names, 'pYNM');
M_.endo_names_tex = char(M_.endo_names_tex, 'pYNM');
M_.endo_names_long = char(M_.endo_names_long, 'pYNM');
M_.endo_names = char(M_.endo_names, 'kappa');
M_.endo_names_tex = char(M_.endo_names_tex, 'kappa');
M_.endo_names_long = char(M_.endo_names_long, 'kappa');
M_.endo_names = char(M_.endo_names, 'varrho');
M_.endo_names_tex = char(M_.endo_names_tex, 'varrho');
M_.endo_names_long = char(M_.endo_names_long, 'varrho');
M_.endo_names = char(M_.endo_names, 'varomega');
M_.endo_names_tex = char(M_.endo_names_tex, 'varomega');
M_.endo_names_long = char(M_.endo_names_long, 'varomega');
M_.endo_names = char(M_.endo_names, 'rhox');
M_.endo_names_tex = char(M_.endo_names_tex, 'rhox');
M_.endo_names_long = char(M_.endo_names_long, 'rhox');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'yCo');
M_.endo_names_tex = char(M_.endo_names_tex, 'yCo');
M_.endo_names_long = char(M_.endo_names_long, 'yCo');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'Rstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rstar');
M_.endo_names_long = char(M_.endo_names_long, 'Rstar');
M_.endo_names = char(M_.endo_names, 'pistar');
M_.endo_names_tex = char(M_.endo_names_tex, 'pistar');
M_.endo_names_long = char(M_.endo_names_long, 'pistar');
M_.endo_names = char(M_.endo_names, 'zetao');
M_.endo_names_tex = char(M_.endo_names_tex, 'zetao');
M_.endo_names_long = char(M_.endo_names_long, 'zetao');
M_.endo_names = char(M_.endo_names, 'zetau');
M_.endo_names_tex = char(M_.endo_names_tex, 'zetau');
M_.endo_names_long = char(M_.endo_names_long, 'zetau');
M_.endo_names = char(M_.endo_names, 'ystar');
M_.endo_names_tex = char(M_.endo_names_tex, 'ystar');
M_.endo_names_long = char(M_.endo_names_long, 'ystar');
M_.endo_names = char(M_.endo_names, 'pCostar');
M_.endo_names_tex = char(M_.endo_names_tex, 'pCostar');
M_.endo_names_long = char(M_.endo_names_long, 'pCostar');
M_.endo_names = char(M_.endo_names, 'eR');
M_.endo_names_tex = char(M_.endo_names_tex, 'eR');
M_.endo_names_long = char(M_.endo_names_long, 'eR');
M_.endo_names = char(M_.endo_names, 'stb');
M_.endo_names_tex = char(M_.endo_names_tex, 'stb');
M_.endo_names_long = char(M_.endo_names_long, 'stb');
M_.endo_names = char(M_.endo_names, 'gam_Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_Y');
M_.endo_names_long = char(M_.endo_names_long, 'gam_Y');
M_.endo_names = char(M_.endo_names, 'gam_C');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_C');
M_.endo_names_long = char(M_.endo_names_long, 'gam_C');
M_.endo_names = char(M_.endo_names, 'gam_I');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_I');
M_.endo_names_long = char(M_.endo_names_long, 'gam_I');
M_.endo_names = char(M_.endo_names, 'gam_W');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_W');
M_.endo_names_long = char(M_.endo_names_long, 'gam_W');
M_.endo_names = char(M_.endo_names, 'pCoyCo');
M_.endo_names_tex = char(M_.endo_names_tex, 'pCoyCo');
M_.endo_names_long = char(M_.endo_names_long, 'pCoyCo');
M_.endo_names = char(M_.endo_names, 'gam_YNM');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_YNM');
M_.endo_names_long = char(M_.endo_names_long, 'gam_YNM');
M_.endo_names = char(M_.endo_names, 'gam_Y_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_Y\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gam_Y_obs');
M_.endo_names = char(M_.endo_names, 'gam_YNM_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_YNM\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gam_YNM_obs');
M_.endo_names = char(M_.endo_names, 'gam_C_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_C\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gam_C_obs');
M_.endo_names = char(M_.endo_names, 'gam_I_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_I\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gam_I_obs');
M_.endo_names = char(M_.endo_names, 'gam_W_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gam\_W\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'gam_W_obs');
M_.endo_names = char(M_.endo_names, 'R_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'R_obs');
M_.endo_names = char(M_.endo_names, 'xi_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'xi_obs');
M_.endo_names = char(M_.endo_names, 'pi_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'pi_obs');
M_.endo_names = char(M_.endo_names, 'rer_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'rer\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'rer_obs');
M_.endo_names = char(M_.endo_names, 'hn_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'hn\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'hn_obs');
M_.endo_names = char(M_.endo_names, 'u_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'u\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'u_obs');
M_.endo_names = char(M_.endo_names, 'pCoyCo_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'pCoyCo\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'pCoyCo_obs');
M_.endo_names = char(M_.endo_names, 'g_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'g_obs');
M_.endo_names = char(M_.endo_names, 'Rstar_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rstar\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Rstar_obs');
M_.endo_names = char(M_.endo_names, 'pistar_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'pistar\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'pistar_obs');
M_.endo_names = char(M_.endo_names, 'ystar_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'ystar\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'ystar_obs');
M_.endo_names = char(M_.endo_names, 'pCostar_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'pCostar\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'pCostar_obs');
M_.endo_partitions = struct();
M_.param_names = 'VARSIGMA';
M_.param_names_tex = 'VARSIGMA';
M_.param_names_long = 'VARSIGMA';
M_.param_names = char(M_.param_names, 'GAMA');
M_.param_names_tex = char(M_.param_names_tex, 'GAMA');
M_.param_names_long = char(M_.param_names_long, 'GAMA');
M_.param_names = char(M_.param_names, 'BETTA');
M_.param_names_tex = char(M_.param_names_tex, 'BETTA');
M_.param_names_long = char(M_.param_names_long, 'BETTA');
M_.param_names = char(M_.param_names, 'SIGMA');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMA');
M_.param_names_long = char(M_.param_names_long, 'SIGMA');
M_.param_names = char(M_.param_names, 'DELTA');
M_.param_names_tex = char(M_.param_names_tex, 'DELTA');
M_.param_names_long = char(M_.param_names_long, 'DELTA');
M_.param_names = char(M_.param_names, 'UPSILON');
M_.param_names_tex = char(M_.param_names_tex, 'UPSILON');
M_.param_names_long = char(M_.param_names_long, 'UPSILON');
M_.param_names = char(M_.param_names, 'MU');
M_.param_names_tex = char(M_.param_names_tex, 'MU');
M_.param_names_long = char(M_.param_names_long, 'MU');
M_.param_names = char(M_.param_names, 'ALPHA');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHA');
M_.param_names_long = char(M_.param_names_long, 'ALPHA');
M_.param_names = char(M_.param_names, 'ETA');
M_.param_names_tex = char(M_.param_names_tex, 'ETA');
M_.param_names_long = char(M_.param_names_long, 'ETA');
M_.param_names = char(M_.param_names, 'ETASTAR');
M_.param_names_tex = char(M_.param_names_tex, 'ETASTAR');
M_.param_names_long = char(M_.param_names_long, 'ETASTAR');
M_.param_names = char(M_.param_names, 'ALPHA_W');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHA\_W');
M_.param_names_long = char(M_.param_names_long, 'ALPHA_W');
M_.param_names = char(M_.param_names, 'VARTHETA_W');
M_.param_names_tex = char(M_.param_names_tex, 'VARTHETA\_W');
M_.param_names_long = char(M_.param_names_long, 'VARTHETA_W');
M_.param_names = char(M_.param_names, 'THETA_W');
M_.param_names_tex = char(M_.param_names_tex, 'THETA\_W');
M_.param_names_long = char(M_.param_names_long, 'THETA_W');
M_.param_names = char(M_.param_names, 'BBAR');
M_.param_names_tex = char(M_.param_names_tex, 'BBAR');
M_.param_names_long = char(M_.param_names_long, 'BBAR');
M_.param_names = char(M_.param_names, 'PHI');
M_.param_names_tex = char(M_.param_names_tex, 'PHI');
M_.param_names_long = char(M_.param_names_long, 'PHI');
M_.param_names = char(M_.param_names, 'OMEGA');
M_.param_names_tex = char(M_.param_names_tex, 'OMEGA');
M_.param_names_long = char(M_.param_names_long, 'OMEGA');
M_.param_names = char(M_.param_names, 'VARPHI');
M_.param_names_tex = char(M_.param_names_tex, 'VARPHI');
M_.param_names_long = char(M_.param_names_long, 'VARPHI');
M_.param_names = char(M_.param_names, 'SIGMA_CTIL');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMA\_CTIL');
M_.param_names_long = char(M_.param_names_long, 'SIGMA_CTIL');
M_.param_names = char(M_.param_names, 'MU_CTIL');
M_.param_names_tex = char(M_.param_names_tex, 'MU\_CTIL');
M_.param_names_long = char(M_.param_names_long, 'MU_CTIL');
M_.param_names = char(M_.param_names, 'MBAR');
M_.param_names_tex = char(M_.param_names_tex, 'MBAR');
M_.param_names_long = char(M_.param_names_long, 'MBAR');
M_.param_names = char(M_.param_names, 'VARTHETA_H');
M_.param_names_tex = char(M_.param_names_tex, 'VARTHETA\_H');
M_.param_names_long = char(M_.param_names_long, 'VARTHETA_H');
M_.param_names = char(M_.param_names, 'THETA_H');
M_.param_names_tex = char(M_.param_names_tex, 'THETA\_H');
M_.param_names_long = char(M_.param_names_long, 'THETA_H');
M_.param_names = char(M_.param_names, 'EPSILON_H');
M_.param_names_tex = char(M_.param_names_tex, 'EPSILON\_H');
M_.param_names_long = char(M_.param_names_long, 'EPSILON_H');
M_.param_names = char(M_.param_names, 'VARTHETA_F');
M_.param_names_tex = char(M_.param_names_tex, 'VARTHETA\_F');
M_.param_names_long = char(M_.param_names_long, 'VARTHETA_F');
M_.param_names = char(M_.param_names, 'THETA_F');
M_.param_names_tex = char(M_.param_names_tex, 'THETA\_F');
M_.param_names_long = char(M_.param_names_long, 'THETA_F');
M_.param_names = char(M_.param_names, 'EPSILON_F');
M_.param_names_tex = char(M_.param_names_tex, 'EPSILON\_F');
M_.param_names_long = char(M_.param_names_long, 'EPSILON_F');
M_.param_names = char(M_.param_names, 'OSTAR');
M_.param_names_tex = char(M_.param_names_tex, 'OSTAR');
M_.param_names_long = char(M_.param_names_long, 'OSTAR');
M_.param_names = char(M_.param_names, 'O');
M_.param_names_tex = char(M_.param_names_tex, 'O');
M_.param_names_long = char(M_.param_names_long, 'O');
M_.param_names = char(M_.param_names, 'CHI');
M_.param_names_tex = char(M_.param_names_tex, 'CHI');
M_.param_names_long = char(M_.param_names_long, 'CHI');
M_.param_names = char(M_.param_names, 'PSI');
M_.param_names_tex = char(M_.param_names_tex, 'PSI');
M_.param_names_long = char(M_.param_names_long, 'PSI');
M_.param_names = char(M_.param_names, 'RHO_R');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_R');
M_.param_names_long = char(M_.param_names_long, 'RHO_R');
M_.param_names = char(M_.param_names, 'ALPHA_PI');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHA\_PI');
M_.param_names_long = char(M_.param_names_long, 'ALPHA_PI');
M_.param_names = char(M_.param_names, 'ALPHA_Y');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHA\_Y');
M_.param_names_long = char(M_.param_names_long, 'ALPHA_Y');
M_.param_names = char(M_.param_names, 'RHO_kappa');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_kappa');
M_.param_names_long = char(M_.param_names_long, 'RHO_kappa');
M_.param_names = char(M_.param_names, 'RHO_varrho');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_varrho');
M_.param_names_long = char(M_.param_names_long, 'RHO_varrho');
M_.param_names = char(M_.param_names, 'RHO_varomega');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_varomega');
M_.param_names_long = char(M_.param_names_long, 'RHO_varomega');
M_.param_names = char(M_.param_names, 'RHO_rhox');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_rhox');
M_.param_names_long = char(M_.param_names_long, 'RHO_rhox');
M_.param_names = char(M_.param_names, 'RHO_z');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_z');
M_.param_names_long = char(M_.param_names_long, 'RHO_z');
M_.param_names = char(M_.param_names, 'RHO_a');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_a');
M_.param_names_long = char(M_.param_names_long, 'RHO_a');
M_.param_names = char(M_.param_names, 'RHO_yCo');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_yCo');
M_.param_names_long = char(M_.param_names_long, 'RHO_yCo');
M_.param_names = char(M_.param_names, 'RHO_g');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_g');
M_.param_names_long = char(M_.param_names_long, 'RHO_g');
M_.param_names = char(M_.param_names, 'RHO_Rstar');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_Rstar');
M_.param_names_long = char(M_.param_names_long, 'RHO_Rstar');
M_.param_names = char(M_.param_names, 'RHO_pistar');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_pistar');
M_.param_names_long = char(M_.param_names_long, 'RHO_pistar');
M_.param_names = char(M_.param_names, 'RHO_zetao');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_zetao');
M_.param_names_long = char(M_.param_names_long, 'RHO_zetao');
M_.param_names = char(M_.param_names, 'RHO_zetau');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_zetau');
M_.param_names_long = char(M_.param_names_long, 'RHO_zetau');
M_.param_names = char(M_.param_names, 'RHO_ystar');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_ystar');
M_.param_names_long = char(M_.param_names_long, 'RHO_ystar');
M_.param_names = char(M_.param_names, 'RHO_pCostar');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_pCostar');
M_.param_names_long = char(M_.param_names_long, 'RHO_pCostar');
M_.param_names = char(M_.param_names, 'RHO_eR');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_eR');
M_.param_names_long = char(M_.param_names_long, 'RHO_eR');
M_.param_names = char(M_.param_names, 'SIG_kappa');
M_.param_names_tex = char(M_.param_names_tex, 'SIG\_kappa');
M_.param_names_long = char(M_.param_names_long, 'SIG_kappa');
M_.param_names = char(M_.param_names, 'SIG_varrho');
M_.param_names_tex = char(M_.param_names_tex, 'SIG\_varrho');
M_.param_names_long = char(M_.param_names_long, 'SIG_varrho');
M_.param_names = char(M_.param_names, 'SIG_varomega');
M_.param_names_tex = char(M_.param_names_tex, 'SIG\_varomega');
M_.param_names_long = char(M_.param_names_long, 'SIG_varomega');
M_.param_names = char(M_.param_names, 'SIG_rhox');
M_.param_names_tex = char(M_.param_names_tex, 'SIG\_rhox');
M_.param_names_long = char(M_.param_names_long, 'SIG_rhox');
M_.param_names = char(M_.param_names, 'SIG_z');
M_.param_names_tex = char(M_.param_names_tex, 'SIG\_z');
M_.param_names_long = char(M_.param_names_long, 'SIG_z');
M_.param_names = char(M_.param_names, 'SIG_a');
M_.param_names_tex = char(M_.param_names_tex, 'SIG\_a');
M_.param_names_long = char(M_.param_names_long, 'SIG_a');
M_.param_names = char(M_.param_names, 'SIG_yCo');
M_.param_names_tex = char(M_.param_names_tex, 'SIG\_yCo');
M_.param_names_long = char(M_.param_names_long, 'SIG_yCo');
M_.param_names = char(M_.param_names, 'SIG_g');
M_.param_names_tex = char(M_.param_names_tex, 'SIG\_g');
M_.param_names_long = char(M_.param_names_long, 'SIG_g');
M_.param_names = char(M_.param_names, 'SIG_Rstar');
M_.param_names_tex = char(M_.param_names_tex, 'SIG\_Rstar');
M_.param_names_long = char(M_.param_names_long, 'SIG_Rstar');
M_.param_names = char(M_.param_names, 'SIG_pistar');
M_.param_names_tex = char(M_.param_names_tex, 'SIG\_pistar');
M_.param_names_long = char(M_.param_names_long, 'SIG_pistar');
M_.param_names = char(M_.param_names, 'SIG_zetao');
M_.param_names_tex = char(M_.param_names_tex, 'SIG\_zetao');
M_.param_names_long = char(M_.param_names_long, 'SIG_zetao');
M_.param_names = char(M_.param_names, 'SIG_zetau');
M_.param_names_tex = char(M_.param_names_tex, 'SIG\_zetau');
M_.param_names_long = char(M_.param_names_long, 'SIG_zetau');
M_.param_names = char(M_.param_names, 'SIG_ystar');
M_.param_names_tex = char(M_.param_names_tex, 'SIG\_ystar');
M_.param_names_long = char(M_.param_names_long, 'SIG_ystar');
M_.param_names = char(M_.param_names, 'SIG_pCostar');
M_.param_names_tex = char(M_.param_names_tex, 'SIG\_pCostar');
M_.param_names_long = char(M_.param_names_long, 'SIG_pCostar');
M_.param_names = char(M_.param_names, 'SIG_eR');
M_.param_names_tex = char(M_.param_names_tex, 'SIG\_eR');
M_.param_names_long = char(M_.param_names_long, 'SIG_eR');
M_.param_names = char(M_.param_names, 'lam_ss');
M_.param_names_tex = char(M_.param_names_tex, 'lam\_ss');
M_.param_names_long = char(M_.param_names_long, 'lam_ss');
M_.param_names = char(M_.param_names, 'q_ss');
M_.param_names_tex = char(M_.param_names_tex, 'q\_ss');
M_.param_names_long = char(M_.param_names_long, 'q_ss');
M_.param_names = char(M_.param_names, 'c_ss');
M_.param_names_tex = char(M_.param_names_tex, 'c\_ss');
M_.param_names_long = char(M_.param_names_long, 'c_ss');
M_.param_names = char(M_.param_names, 'i_ss');
M_.param_names_tex = char(M_.param_names_tex, 'i\_ss');
M_.param_names_long = char(M_.param_names_long, 'i_ss');
M_.param_names = char(M_.param_names, 'k_ss');
M_.param_names_tex = char(M_.param_names_tex, 'k\_ss');
M_.param_names_long = char(M_.param_names_long, 'k_ss');
M_.param_names = char(M_.param_names, 'theta_ss');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_ss');
M_.param_names_long = char(M_.param_names_long, 'theta_ss');
M_.param_names = char(M_.param_names, 'chitil_ss');
M_.param_names_tex = char(M_.param_names_tex, 'chitil\_ss');
M_.param_names_long = char(M_.param_names_long, 'chitil_ss');
M_.param_names = char(M_.param_names, 'u_ss');
M_.param_names_tex = char(M_.param_names_tex, 'u\_ss');
M_.param_names_long = char(M_.param_names_long, 'u_ss');
M_.param_names = char(M_.param_names, 'm_ss');
M_.param_names_tex = char(M_.param_names_tex, 'm\_ss');
M_.param_names_long = char(M_.param_names_long, 'm_ss');
M_.param_names = char(M_.param_names, 'n_ss');
M_.param_names_tex = char(M_.param_names_tex, 'n\_ss');
M_.param_names_long = char(M_.param_names_long, 'n_ss');
M_.param_names = char(M_.param_names, 'rho_ss');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ss');
M_.param_names_long = char(M_.param_names_long, 'rho_ss');
M_.param_names = char(M_.param_names, 's_ss');
M_.param_names_tex = char(M_.param_names_tex, 's\_ss');
M_.param_names_long = char(M_.param_names_long, 's_ss');
M_.param_names = char(M_.param_names, 'e_ss');
M_.param_names_tex = char(M_.param_names_tex, 'e\_ss');
M_.param_names_long = char(M_.param_names_long, 'e_ss');
M_.param_names = char(M_.param_names, 'thetaL_ss');
M_.param_names_tex = char(M_.param_names_tex, 'thetaL\_ss');
M_.param_names_long = char(M_.param_names_long, 'thetaL_ss');
M_.param_names = char(M_.param_names, 'Ebar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Ebar\_ss');
M_.param_names_long = char(M_.param_names_long, 'Ebar_ss');
M_.param_names = char(M_.param_names, 'Estar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Estar\_ss');
M_.param_names_long = char(M_.param_names_long, 'Estar_ss');
M_.param_names = char(M_.param_names, 'U_ss');
M_.param_names_tex = char(M_.param_names_tex, 'U\_ss');
M_.param_names_long = char(M_.param_names_long, 'U_ss');
M_.param_names = char(M_.param_names, 'Delbar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Delbar\_ss');
M_.param_names_long = char(M_.param_names_long, 'Delbar_ss');
M_.param_names = char(M_.param_names, 'Delstar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Delstar\_ss');
M_.param_names_long = char(M_.param_names_long, 'Delstar_ss');
M_.param_names = char(M_.param_names, 'wstar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'wstar\_ss');
M_.param_names_long = char(M_.param_names_long, 'wstar_ss');
M_.param_names = char(M_.param_names, 'epsi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'epsi\_ss');
M_.param_names_long = char(M_.param_names_long, 'epsi_ss');
M_.param_names = char(M_.param_names, 'mu_ss');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_ss');
M_.param_names_long = char(M_.param_names_long, 'mu_ss');
M_.param_names = char(M_.param_names, 'Fstar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Fstar\_ss');
M_.param_names_long = char(M_.param_names_long, 'Fstar_ss');
M_.param_names = char(M_.param_names, 'Wstar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Wstar\_ss');
M_.param_names_long = char(M_.param_names_long, 'Wstar_ss');
M_.param_names = char(M_.param_names, 'Wbar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Wbar\_ss');
M_.param_names_long = char(M_.param_names_long, 'Wbar_ss');
M_.param_names = char(M_.param_names, 'w_ss');
M_.param_names_tex = char(M_.param_names_tex, 'w\_ss');
M_.param_names_long = char(M_.param_names_long, 'w_ss');
M_.param_names = char(M_.param_names, 'wbar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'wbar\_ss');
M_.param_names_long = char(M_.param_names_long, 'wbar_ss');
M_.param_names = char(M_.param_names, 'wtil_ss');
M_.param_names_tex = char(M_.param_names_tex, 'wtil\_ss');
M_.param_names_long = char(M_.param_names_long, 'wtil_ss');
M_.param_names = char(M_.param_names, 'h_ss');
M_.param_names_tex = char(M_.param_names_tex, 'h\_ss');
M_.param_names_long = char(M_.param_names_long, 'h_ss');
M_.param_names = char(M_.param_names, 'yC_ss');
M_.param_names_tex = char(M_.param_names_tex, 'yC\_ss');
M_.param_names_long = char(M_.param_names_long, 'yC_ss');
M_.param_names = char(M_.param_names, 'xH_ss');
M_.param_names_tex = char(M_.param_names_tex, 'xH\_ss');
M_.param_names_long = char(M_.param_names_long, 'xH_ss');
M_.param_names = char(M_.param_names, 'xF_ss');
M_.param_names_tex = char(M_.param_names_tex, 'xF\_ss');
M_.param_names_long = char(M_.param_names_long, 'xF_ss');
M_.param_names = char(M_.param_names, 'yH_ss');
M_.param_names_tex = char(M_.param_names_tex, 'yH\_ss');
M_.param_names_long = char(M_.param_names_long, 'yH_ss');
M_.param_names = char(M_.param_names, 'yF_ss');
M_.param_names_tex = char(M_.param_names_tex, 'yF\_ss');
M_.param_names_long = char(M_.param_names_long, 'yF_ss');
M_.param_names = char(M_.param_names, 'pm_ss');
M_.param_names_tex = char(M_.param_names_tex, 'pm\_ss');
M_.param_names_long = char(M_.param_names_long, 'pm_ss');
M_.param_names = char(M_.param_names, 'ptilH_ss');
M_.param_names_tex = char(M_.param_names_tex, 'ptilH\_ss');
M_.param_names_long = char(M_.param_names_long, 'ptilH_ss');
M_.param_names = char(M_.param_names, 'ptilF_ss');
M_.param_names_tex = char(M_.param_names_tex, 'ptilF\_ss');
M_.param_names_long = char(M_.param_names_long, 'ptilF_ss');
M_.param_names = char(M_.param_names, 'fH_ss');
M_.param_names_tex = char(M_.param_names_tex, 'fH\_ss');
M_.param_names_long = char(M_.param_names_long, 'fH_ss');
M_.param_names = char(M_.param_names, 'fF_ss');
M_.param_names_tex = char(M_.param_names_tex, 'fF\_ss');
M_.param_names_long = char(M_.param_names_long, 'fF_ss');
M_.param_names = char(M_.param_names, 'mcH_ss');
M_.param_names_tex = char(M_.param_names_tex, 'mcH\_ss');
M_.param_names_long = char(M_.param_names_long, 'mcH_ss');
M_.param_names = char(M_.param_names, 'mcF_ss');
M_.param_names_tex = char(M_.param_names_tex, 'mcF\_ss');
M_.param_names_long = char(M_.param_names_long, 'mcF_ss');
M_.param_names = char(M_.param_names, 'rK_ss');
M_.param_names_tex = char(M_.param_names_tex, 'rK\_ss');
M_.param_names_long = char(M_.param_names_long, 'rK_ss');
M_.param_names = char(M_.param_names, 'v_ss');
M_.param_names_tex = char(M_.param_names_tex, 'v\_ss');
M_.param_names_long = char(M_.param_names_long, 'v_ss');
M_.param_names = char(M_.param_names, 'rhon_ss');
M_.param_names_tex = char(M_.param_names_tex, 'rhon\_ss');
M_.param_names_long = char(M_.param_names_long, 'rhon_ss');
M_.param_names = char(M_.param_names, 'ctil_ss');
M_.param_names_tex = char(M_.param_names_tex, 'ctil\_ss');
M_.param_names_long = char(M_.param_names_long, 'ctil_ss');
M_.param_names = char(M_.param_names, 'hC_ss');
M_.param_names_tex = char(M_.param_names_tex, 'hC\_ss');
M_.param_names_long = char(M_.param_names_long, 'hC_ss');
M_.param_names = char(M_.param_names, 'imp_ss');
M_.param_names_tex = char(M_.param_names_tex, 'imp\_ss');
M_.param_names_long = char(M_.param_names_long, 'imp_ss');
M_.param_names = char(M_.param_names, 'pi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'pi\_ss');
M_.param_names_long = char(M_.param_names_long, 'pi_ss');
M_.param_names = char(M_.param_names, 'R_ss');
M_.param_names_tex = char(M_.param_names_tex, 'R\_ss');
M_.param_names_long = char(M_.param_names_long, 'R_ss');
M_.param_names = char(M_.param_names, 'xi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_ss');
M_.param_names_long = char(M_.param_names_long, 'xi_ss');
M_.param_names = char(M_.param_names, 'rer_ss');
M_.param_names_tex = char(M_.param_names_tex, 'rer\_ss');
M_.param_names_long = char(M_.param_names_long, 'rer_ss');
M_.param_names = char(M_.param_names, 'piS_ss');
M_.param_names_tex = char(M_.param_names_tex, 'piS\_ss');
M_.param_names_long = char(M_.param_names_long, 'piS_ss');
M_.param_names = char(M_.param_names, 'xHstar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'xHstar\_ss');
M_.param_names_long = char(M_.param_names_long, 'xHstar_ss');
M_.param_names = char(M_.param_names, 'pH_ss');
M_.param_names_tex = char(M_.param_names_tex, 'pH\_ss');
M_.param_names_long = char(M_.param_names_long, 'pH_ss');
M_.param_names = char(M_.param_names, 'pF_ss');
M_.param_names_tex = char(M_.param_names_tex, 'pF\_ss');
M_.param_names_long = char(M_.param_names_long, 'pF_ss');
M_.param_names = char(M_.param_names, 'DelH_ss');
M_.param_names_tex = char(M_.param_names_tex, 'DelH\_ss');
M_.param_names_long = char(M_.param_names_long, 'DelH_ss');
M_.param_names = char(M_.param_names, 'DelF_ss');
M_.param_names_tex = char(M_.param_names_tex, 'DelF\_ss');
M_.param_names_long = char(M_.param_names_long, 'DelF_ss');
M_.param_names = char(M_.param_names, 'dstar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'dstar\_ss');
M_.param_names_long = char(M_.param_names_long, 'dstar_ss');
M_.param_names = char(M_.param_names, 'tb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'tb\_ss');
M_.param_names_long = char(M_.param_names_long, 'tb_ss');
M_.param_names = char(M_.param_names, 'y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'y\_ss');
M_.param_names_long = char(M_.param_names_long, 'y_ss');
M_.param_names = char(M_.param_names, 'yNM_ss');
M_.param_names_tex = char(M_.param_names_tex, 'yNM\_ss');
M_.param_names_long = char(M_.param_names_long, 'yNM_ss');
M_.param_names = char(M_.param_names, 'pY_ss');
M_.param_names_tex = char(M_.param_names_tex, 'pY\_ss');
M_.param_names_long = char(M_.param_names_long, 'pY_ss');
M_.param_names = char(M_.param_names, 'pYNM_ss');
M_.param_names_tex = char(M_.param_names_tex, 'pYNM\_ss');
M_.param_names_long = char(M_.param_names_long, 'pYNM_ss');
M_.param_names = char(M_.param_names, 'kappa_ss');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_ss');
M_.param_names_long = char(M_.param_names_long, 'kappa_ss');
M_.param_names = char(M_.param_names, 'varrho_ss');
M_.param_names_tex = char(M_.param_names_tex, 'varrho\_ss');
M_.param_names_long = char(M_.param_names_long, 'varrho_ss');
M_.param_names = char(M_.param_names, 'varomega_ss');
M_.param_names_tex = char(M_.param_names_tex, 'varomega\_ss');
M_.param_names_long = char(M_.param_names_long, 'varomega_ss');
M_.param_names = char(M_.param_names, 'rhox_ss');
M_.param_names_tex = char(M_.param_names_tex, 'rhox\_ss');
M_.param_names_long = char(M_.param_names_long, 'rhox_ss');
M_.param_names = char(M_.param_names, 'z_ss');
M_.param_names_tex = char(M_.param_names_tex, 'z\_ss');
M_.param_names_long = char(M_.param_names_long, 'z_ss');
M_.param_names = char(M_.param_names, 'a_ss');
M_.param_names_tex = char(M_.param_names_tex, 'a\_ss');
M_.param_names_long = char(M_.param_names_long, 'a_ss');
M_.param_names = char(M_.param_names, 'yCo_ss');
M_.param_names_tex = char(M_.param_names_tex, 'yCo\_ss');
M_.param_names_long = char(M_.param_names_long, 'yCo_ss');
M_.param_names = char(M_.param_names, 'g_ss');
M_.param_names_tex = char(M_.param_names_tex, 'g\_ss');
M_.param_names_long = char(M_.param_names_long, 'g_ss');
M_.param_names = char(M_.param_names, 'Rstar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rstar\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rstar_ss');
M_.param_names = char(M_.param_names, 'pistar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'pistar\_ss');
M_.param_names_long = char(M_.param_names_long, 'pistar_ss');
M_.param_names = char(M_.param_names, 'zetao_ss');
M_.param_names_tex = char(M_.param_names_tex, 'zetao\_ss');
M_.param_names_long = char(M_.param_names_long, 'zetao_ss');
M_.param_names = char(M_.param_names, 'zetau_ss');
M_.param_names_tex = char(M_.param_names_tex, 'zetau\_ss');
M_.param_names_long = char(M_.param_names_long, 'zetau_ss');
M_.param_names = char(M_.param_names, 'ystar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'ystar\_ss');
M_.param_names_long = char(M_.param_names_long, 'ystar_ss');
M_.param_names = char(M_.param_names, 'pCostar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'pCostar\_ss');
M_.param_names_long = char(M_.param_names_long, 'pCostar_ss');
M_.param_names = char(M_.param_names, 'eR_ss');
M_.param_names_tex = char(M_.param_names_tex, 'eR\_ss');
M_.param_names_long = char(M_.param_names_long, 'eR_ss');
M_.param_names = char(M_.param_names, 'stb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'stb\_ss');
M_.param_names_long = char(M_.param_names_long, 'stb_ss');
M_.param_names = char(M_.param_names, 'sg_ss');
M_.param_names_tex = char(M_.param_names_tex, 'sg\_ss');
M_.param_names_long = char(M_.param_names_long, 'sg_ss');
M_.param_names = char(M_.param_names, 'sCo_ss');
M_.param_names_tex = char(M_.param_names_tex, 'sCo\_ss');
M_.param_names_long = char(M_.param_names_long, 'sCo_ss');
M_.param_names = char(M_.param_names, 'pCoyCo_ss');
M_.param_names_tex = char(M_.param_names_tex, 'pCoyCo\_ss');
M_.param_names_long = char(M_.param_names_long, 'pCoyCo_ss');
M_.param_names = char(M_.param_names, 'pYy_ss');
M_.param_names_tex = char(M_.param_names_tex, 'pYy\_ss');
M_.param_names_long = char(M_.param_names_long, 'pYy_ss');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 16;
M_.endo_nbr = 102;
M_.param_nbr = 146;
M_.orig_endo_nbr = 102;
M_.aux_vars = [];
options_.varobs = cell(1);
options_.varobs(1)  = {'gam_YNM_obs'};
options_.varobs(2)  = {'gam_C_obs'};
options_.varobs(3)  = {'gam_I_obs'};
options_.varobs(4)  = {'gam_W_obs'};
options_.varobs(5)  = {'R_obs'};
options_.varobs(6)  = {'xi_obs'};
options_.varobs(7)  = {'pi_obs'};
options_.varobs(8)  = {'rer_obs'};
options_.varobs(9)  = {'u_obs'};
options_.varobs(10)  = {'hn_obs'};
options_.varobs(11)  = {'pCoyCo_obs'};
options_.varobs(12)  = {'g_obs'};
options_.varobs(13)  = {'Rstar_obs'};
options_.varobs(14)  = {'pistar_obs'};
options_.varobs(15)  = {'ystar_obs'};
options_.varobs(16)  = {'pCostar_obs'};
options_.varobs_id = [ 87 88 89 90 91 92 93 94 96 95 97 98 99 100 101 102  ];
M_.Sigma_e = zeros(16, 16);
M_.Correlation_matrix = eye(16, 16);
M_.H = zeros(16, 16);
M_.Correlation_matrix_ME = eye(16, 16);
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('Search_irf_static');
erase_compiled_function('Search_irf_dynamic');
M_.orig_eq_nbr = 102;
M_.eq_nbr = 102;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 39 141;
 0 40 142;
 1 41 0;
 2 42 143;
 3 43 0;
 0 44 0;
 4 45 0;
 0 46 0;
 5 47 0;
 6 48 144;
 0 49 145;
 7 50 0;
 0 51 146;
 0 52 0;
 0 53 147;
 0 54 148;
 0 55 149;
 0 56 150;
 0 57 151;
 8 58 152;
 0 59 153;
 0 60 154;
 0 61 0;
 0 62 155;
 0 63 156;
 9 64 157;
 0 65 0;
 10 66 0;
 0 67 158;
 0 68 0;
 0 69 0;
 0 70 0;
 0 71 159;
 0 72 0;
 0 73 160;
 0 74 161;
 0 75 162;
 0 76 163;
 0 77 164;
 0 78 0;
 0 79 0;
 0 80 165;
 0 81 0;
 0 82 0;
 0 83 0;
 0 84 166;
 0 85 0;
 11 86 167;
 12 87 0;
 13 88 0;
 14 89 0;
 0 90 168;
 0 91 0;
 15 92 169;
 16 93 170;
 17 94 171;
 18 95 0;
 19 96 0;
 0 97 0;
 20 98 0;
 21 99 0;
 22 100 0;
 23 101 0;
 24 102 0;
 25 103 172;
 26 104 173;
 27 105 0;
 28 106 0;
 29 107 174;
 30 108 0;
 31 109 0;
 32 110 0;
 33 111 0;
 34 112 0;
 35 113 0;
 36 114 0;
 37 115 0;
 38 116 0;
 0 117 0;
 0 118 0;
 0 119 0;
 0 120 0;
 0 121 0;
 0 122 0;
 0 123 0;
 0 124 0;
 0 125 0;
 0 126 0;
 0 127 0;
 0 128 0;
 0 129 0;
 0 130 0;
 0 131 0;
 0 132 0;
 0 133 0;
 0 134 0;
 0 135 0;
 0 136 0;
 0 137 0;
 0 138 0;
 0 139 0;
 0 140 0;]';
M_.nstatic = 41;
M_.nfwrd   = 23;
M_.npred   = 27;
M_.nboth   = 11;
M_.nsfwrd   = 34;
M_.nspred   = 38;
M_.ndynamic   = 61;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:16];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(102, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(16, 1);
M_.params = NaN(146, 1);
M_.NNZDerivatives = [560; -1; -1];
close all;
M_.params( 4 ) = 1;
SIGMA = M_.params( 4 );
M_.params( 3 ) = 0.9995;
BETTA = M_.params( 3 );
M_.params( 8 ) = 0.34;
ALPHA = M_.params( 8 );
M_.params( 5 ) = 0.015;
DELTA = M_.params( 5 );
M_.params( 23 ) = 11;
EPSILON_H = M_.params( 23 );
M_.params( 26 ) = 11;
EPSILON_F = M_.params( 26 );
M_.params( 11 ) = 1;
ALPHA_W = M_.params( 11 );
M_.params( 28 ) = 0.32;
O = M_.params( 28 );
M_.params( 29 ) = 0.61;
CHI = M_.params( 29 );
M_.params( 19 ) = 0;
MU_CTIL = M_.params( 19 );
M_.params( 48 ) = 0;
RHO_eR = M_.params( 48 );
M_.params( 142 ) = 0.04;
stb_ss = M_.params( 142 );
M_.params( 143 ) = 0.11;
sg_ss = M_.params( 143 );
M_.params( 144 ) = 0.10;
sCo_ss = M_.params( 144 );
M_.params( 111 ) = 1.007417071777733;
pi_ss = M_.params( 111 );
M_.params( 132 ) = 1.004962931573204;
a_ss = M_.params( 132 );
M_.params( 135 ) = 1.011064990499149;
Rstar_ss = M_.params( 135 );
M_.params( 113 ) = 1.003729088938093;
xi_ss = M_.params( 113 );
M_.params( 71 ) = 0.08;
u_ss = M_.params( 71 );
M_.params( 76 ) = 0.7;
e_ss = M_.params( 76 );
M_.params( 74 ) = 0.07547169811320754;
rho_ss = M_.params( 74 );
M_.params( 130 ) = 2*M_.params(74)/3;
rhox_ss = M_.params( 130 );
M_.params( 128 ) = 1;
varrho_ss = M_.params( 128 );
M_.params( 129 ) = 1;
varomega_ss = M_.params( 129 );
M_.params( 131 ) = 1;
z_ss = M_.params( 131 );
M_.params( 137 ) = 1;
zetao_ss = M_.params( 137 );
M_.params( 138 ) = 1;
zetau_ss = M_.params( 138 );
M_.params( 139 ) = 1;
ystar_ss = M_.params( 139 );
M_.params( 141 ) = 1;
eR_ss = M_.params( 141 );
M_.params( 140 ) = 1;
pCostar_ss = M_.params( 140 );
M_.params( 117 ) = 1;
pH_ss = M_.params( 117 );
M_.params( 92 ) = 1;
h_ss = M_.params( 92 );
M_.params( 41 ) = 0.8057;
RHO_g = M_.params( 41 );
M_.params( 42 ) = 0.9677;
RHO_Rstar = M_.params( 42 );
M_.params( 43 ) = 0.4488;
RHO_pistar = M_.params( 43 );
M_.params( 46 ) = 0.8748;
RHO_ystar = M_.params( 46 );
M_.params( 47 ) = 0.9637;
RHO_pCostar = M_.params( 47 );
M_.params( 56 ) = 0.0186;
SIG_g = M_.params( 56 );
M_.params( 57 ) = 0.0010;
SIG_Rstar = M_.params( 57 );
M_.params( 58 ) = 0.0259;
SIG_pistar = M_.params( 58 );
M_.params( 61 ) = 0.0054;
SIG_ystar = M_.params( 61 );
M_.params( 62 ) = 0.1271;
SIG_pCostar = M_.params( 62 );
M_.params( 6 ) = 0.104341405;
UPSILON = M_.params( 6 );
M_.params( 15 ) = 5.094580172;
PHI = M_.params( 15 );
M_.params( 1 ) = 0.745154441;
VARSIGMA = M_.params( 1 );
M_.params( 2 ) = 0.805587274;
GAMA = M_.params( 2 );
M_.params( 9 ) = 3.525953529;
ETA = M_.params( 9 );
M_.params( 30 ) = 0.005311765;
PSI = M_.params( 30 );
M_.params( 10 ) = 0.227473018;
ETASTAR = M_.params( 10 );
M_.params( 17 ) = 0.268826336;
VARPHI = M_.params( 17 );
M_.params( 7 ) = 0.747640825;
MU = M_.params( 7 );
M_.params( 18 ) = 0.30152978;
SIGMA_CTIL = M_.params( 18 );
M_.params( 13 ) = 0.7787198;
THETA_W = M_.params( 13 );
M_.params( 12 ) = 0.236594212;
VARTHETA_W = M_.params( 12 );
M_.params( 22 ) = 0.328768341;
THETA_H = M_.params( 22 );
M_.params( 21 ) = 0.509342846;
VARTHETA_H = M_.params( 21 );
M_.params( 25 ) = 0.818346665;
THETA_F = M_.params( 25 );
M_.params( 24 ) = 0.635874799;
VARTHETA_F = M_.params( 24 );
M_.params( 31 ) = 0.826800084;
RHO_R = M_.params( 31 );
M_.params( 32 ) = 1.545701592;
ALPHA_PI = M_.params( 32 );
M_.params( 33 ) = 0.154473528;
ALPHA_Y = M_.params( 33 );
M_.params( 34 ) = 0.75;
RHO_kappa = M_.params( 34 );
0.771547576; 
M_.params( 35 ) = 0.75;
RHO_varrho = M_.params( 35 );
0.639468789; 
M_.params( 36 ) = 0.75;
RHO_varomega = M_.params( 36 );
0.647259486; 
M_.params( 37 ) = 0.75;
RHO_rhox = M_.params( 37 );
0.877520566;
M_.params( 38 ) = 0.75;
RHO_z = M_.params( 38 );
0.717311389; 
M_.params( 39 ) = 0.375;
RHO_a = M_.params( 39 );
0.347204443; 
M_.params( 40 ) = 0.75;
RHO_yCo = M_.params( 40 );
0.948801805; 
M_.params( 44 ) = 0.75;
RHO_zetao = M_.params( 44 );
0.873638845; 
M_.params( 45 ) = 0.75;
RHO_zetau = M_.params( 45 );
0.773949583; 
M_.params( 49 ) = 0.01;
SIG_kappa = M_.params( 49 );
0.030253667; 
M_.params( 50 ) = 0.01;
SIG_varrho = M_.params( 50 );
0.0413235; 
M_.params( 51 ) = 0.01;
SIG_varomega = M_.params( 51 );
0.025738754; 
M_.params( 52 ) = 0.01;
SIG_rhox = M_.params( 52 );
0.152269856;
M_.params( 53 ) = 0.01;
SIG_z = M_.params( 53 );
0.007196123; 
M_.params( 54 ) = 0.01;
SIG_a = M_.params( 54 );
0.003037889; 
M_.params( 55 ) = 0.01;
SIG_yCo = M_.params( 55 );
0.066067589; 
M_.params( 59 ) = 0.0025;
SIG_zetao = M_.params( 59 );
0.01; 0.000760844;
M_.params( 60 ) = 0.0025;
SIG_zetau = M_.params( 60 );
0.01; 0.007275765;
M_.params( 63 ) = 0.0025;
SIG_eR = M_.params( 63 );
0.01; 0.001662937;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (M_.params(49))^2;
M_.Sigma_e(2, 2) = (M_.params(50))^2;
M_.Sigma_e(3, 3) = (M_.params(51))^2;
M_.Sigma_e(4, 4) = (M_.params(52))^2;
M_.Sigma_e(5, 5) = (M_.params(53))^2;
M_.Sigma_e(6, 6) = (M_.params(54))^2;
M_.Sigma_e(7, 7) = (M_.params(55))^2;
M_.Sigma_e(8, 8) = (M_.params(56))^2;
M_.Sigma_e(9, 9) = (M_.params(57))^2;
M_.Sigma_e(10, 10) = (M_.params(58))^2;
M_.Sigma_e(11, 11) = (M_.params(59))^2;
M_.Sigma_e(12, 12) = (M_.params(60))^2;
M_.Sigma_e(13, 13) = (M_.params(61))^2;
M_.Sigma_e(14, 14) = (M_.params(62))^2;
M_.Sigma_e(15, 15) = (M_.params(63))^2;
M_.Sigma_e(16, 16) = (eps)^2;
M_.H(1, 1) = (0.3616696959934576)^2;
M_.H(2, 2) = (0.3814023085929082)^2;
M_.H(3, 3) = (1.187182279180413)^2;
M_.H(4, 4) = (0.1848983747900451)^2;
M_.H(5, 5) = (0)^2;
M_.H(6, 6) = (0.04639061327467012)^2;
M_.H(7, 7) = (0.2187031229772451)^2;
M_.H(8, 8) = (1.634233471998417)^2;
M_.H(10, 10) = (0.5910296946854701)^2;
M_.H(9, 9) = (0.4519843459678665)^2;
M_.H(11, 11) = (13.07527577379097)^2;
estim_params_.var_exo = [];
estim_params_.var_endo = [];
estim_params_.corrx = [];
estim_params_.corrn = [];
estim_params_.param_vals = [];
estim_params_.param_vals = [estim_params_.param_vals; 6, NaN, (-Inf), Inf, 1, 0.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, NaN, 0, NaN, 3, 2, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 1, NaN, (-Inf), Inf, 1, 0.7, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 2, NaN, (-Inf), Inf, 3, 4, 1.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, NaN, (-Inf), Inf, 4, 1.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 30, NaN, (-Inf), Inf, 4, 0.01, Inf, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, NaN, (-Inf), Inf, 4, 0.25, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, NaN, 0, NaN, 3, 0.1, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, NaN, (-Inf), Inf, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, NaN, (-Inf), Inf, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 25, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, NaN, (-Inf), Inf, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 31, NaN, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 32, NaN, 1, NaN, 3, 1.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 33, NaN, 0, NaN, 3, 0.125, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 34, NaN, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 35, NaN, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 36, NaN, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 37, NaN, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 38, NaN, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 39, NaN, (-Inf), Inf, 1, 0.375, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 40, NaN, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 44, NaN, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 45, NaN, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, NaN, (-Inf), Inf, 4, 0.01, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, NaN, (-Inf), Inf, 4, 0.01, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, NaN, (-Inf), Inf, 4, 0.01, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, NaN, (-Inf), Inf, 4, 0.01, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, NaN, (-Inf), Inf, 4, 0.01, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, NaN, (-Inf), Inf, 4, 0.01, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, NaN, (-Inf), Inf, 4, 0.01, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 11, NaN, (-Inf), Inf, 4, 0.0025, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 12, NaN, (-Inf), Inf, 4, 0.0025, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 15, NaN, (-Inf), Inf, 4, 0.0025, Inf, NaN, NaN, NaN ];
options_.irf = 40;
options_.nograph = 1;
options_.order = 1;
options_.periods = 0;
var_list_ = char();
info = stoch_simul(var_list_);
save('Search_irf_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('Search_irf_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('Search_irf_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('Search_irf_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('Search_irf_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('Search_irf_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('Search_irf_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
disp('Note: 1 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
